spring:
  redis:
    database: 0
#    host: 47.94.134.137
#    port: 6370
    password: ice
     #redis集群模式
#    cluster:
#      max-redirects: 3
#      nodes:
#        - 47.94.134.137:7000
#        - 47.94.134.137:7001
#        - 47.94.134.137:7002
#        - 47.94.134.137:7003
#        - 47.94.134.137:7004
#        - 47.94.134.137:7005
    #redis哨兵模式
    sentinel:
       master: mymaster
       nodes: 
         - 47.94.134.137:7014
         - 47.94.134.137:7015
         - 47.94.134.137:7016
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000